# Please refer https://docs.docker.com/compose to learn more about Docker Compose.

version: '3.4'

services:
  TestServer:
    image: test-server
    build:
      context: .
      dockerfile: TestServer/Dockerfile