
name: Docker-Test Continuous Integration

on:
  push:
    branches:
      - '**'

    paths:
    - '.github/workflows/docker-ci.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v2
    - name: Build and Test Docker images
      run: |
        docker-compose -f src/docker-compose.yml up